Added Barcode scanner icon and functionality to persistent searchbar
shopgate-professional-services/ext-persistent-search-bar pull request #3
Opened 2019-11-11 17:16 UTC by dqdquint

The barcode scanner svg will appear depending on the showSearchFieldIcon config that is set in the Merchant connect admin.

2019-11-12 13:32 UTC, aaron-martin commented
I see this error when doing a search in the browser console. 
![image](https://user-images.githubusercontent.com/11764719/68675965-9da1b600-051e-11ea-9294-8231ecdc3c55.png)

2019-11-12 13:33 UTC, aaron-martin requested changes
Generally it looks good. Please investigate the console log error I am seeing. I don't see this when I do a search and the extension is not attached.

2019-11-12 18:32 UTC, dqdquint commented
Found the solution to the error above. Thanks @aaron-martin

2019-11-13 12:17 UTC, aaron-martin approved these changes

2019-11-14 20:27 UTC, merged